### DISCUSSION TITLE
How to MACVLAN and Redis on same iobroker instance?

### DISCUSSION THREAD

**Discussion by manoloxxl** [buanet/ioBroker.docker#326] [Questions & Answers / Fragen & Antworten] [answered]
### Description

Hi,

I am running the image on docker with macvlan ip in my home network. I want to connect it to a redis db that is running in same docker, but in a internal bridge mode.

I know, that i can add the macvlan and internal bridge to the iob container, but then i'm running into issues with the BLE adapter. 

I removed the internal bridge from iob and try to reach the redis by using the docker-ip and forwared port 6379. But it's not reachable.

This is a bit strange as i can reach from my desktop a influxdb, that is also running in the dockers internal brige with forwared port 8086 by using docker-ip:8086

So iob should, as it also in the home network, reach the redis.

I am not sure how to handle this. I could give the redis also a macvlan, but i don't think this should be necesary.

How can i fix this?

Best Regards

### Image version

7.20

### Docker logs

```shell
Setting up libasound2-data (1.2.4-1.1) ...
Setting up dbus (1.12.24-0+deb11u1) ...
invoke-rc.d: could not determine current runlevel
invoke-rc.d: policy-rc.d denied execution of start.
Setting up alsa-topology-conf (1.2.4-1) ...
Setting up libasound2:amd64 (1.2.4-1.1) ...
Setting up alsa-ucm-conf (1.2.4-2) ...
Setting up bluez (5.55-3.1) ...
invoke-rc.d: could not determine current runlevel
invoke-rc.d: policy-rc.d denied execution of force-reload.
invoke-rc.d: could not determine current runlevel
invoke-rc.d: policy-rc.d denied execution of start.
Setting up bluetooth (5.55-3.1) ...
Processing triggers for libc-bin (2.31-13+deb11u5) ...
Processing triggers for dbus (1.12.24-0+deb11u1) ...
Done.
bluez is already installed.
libbluetooth-dev is not installed. Installing...
debconf: unable to initialize frontend: Dialog
debconf: (Dialog frontend will not work on a dumb terminal, an emacs shell buffer, or without a controlling terminal.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin: 
Selecting previously unselected package libbluetooth3:amd64.
(Reading database ... 
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 30712 files and directories currently installed.)
Preparing to unpack .../libbluetooth3_5.55-3.1_amd64.deb ...
Unpacking libbluetooth3:amd64 (5.55-3.1) ...
Selecting previously unselected package libbluetooth-dev:amd64.
Preparing to unpack .../libbluetooth-dev_5.55-3.1_amd64.deb ...
Unpacking libbluetooth-dev:amd64 (5.55-3.1) ...
Setting up libbluetooth3:amd64 (5.55-3.1) ...
Setting up libbluetooth-dev:amd64 (5.55-3.1) ...
Processing triggers for libc-bin (2.31-13+deb11u5) ...
Done.
libudev-dev is already installed.
net-tools is already installed.
Done.
 
Registering maintenance script as command... Done.
 
--------------------------------------------------------------------------------
-----             Step 2 of 5: Detecting ioBroker installation             -----
--------------------------------------------------------------------------------
 
Existing installation of ioBroker detected in "/opt/iobroker".
 
--------------------------------------------------------------------------------
-----             Step 3 of 5: Checking ioBroker installation              -----
--------------------------------------------------------------------------------
 
(Re)setting permissions (This might take a while! Please be patient!)... Done.
 
Fixing "sudo-bug" by replacing sudo with gosu... Done.
 
Hostname in ioBroker does not match the hostname of this container.
Updating hostname to iobrokerW54... The host for instance "system.adapter.admin.0" was changed from "buildkitsandbox" to "iobrokerW54".
The host for instance "system.adapter.discovery.0" was changed from "buildkitsandbox" to "iobrokerW54".
The host for instance "system.adapter.backitup.0" was changed from "buildkitsandbox" to "iobrokerW54".
Done.
 
--------------------------------------------------------------------------------
-----                Step 4 of 5: Applying special settings                -----
--------------------------------------------------------------------------------
 
Some adapters have special requirements/ settings which can be activated by the use of environment variables.
For more information see ioBroker Docker Image Docs (https://docs.buanet.de/iobroker-docker-image/docs/).
 
Userscript for first start detected and this is the first start of a new container.
Running userscript_firststart.sh... 
 
I'm your startscript userscript_firststart.sh. I will run only on the FIRST startup of the container.
 
Done.
 
Userscript for every start detected. Running userscript_everystart.sh... 
 
I'm your startscript userscript_everystart.sh. I will run on EVERY container startup.
 
Starting system message bus: dbus.
Starting bluetooth: bluetoothd.
Can't open HCI socket.: Address family not supported by protocol
Done.
 
--------------------------------------------------------------------------------
-----                    Step 5 of 5: ioBroker startup                     -----
--------------------------------------------------------------------------------
 
Starting ioBroker... 
 
##### #### ### ## # iobroker.js-controller log output # ## ### #### #####
host.iobrokerW54 check instance "system.adapter.admin.0" for host "iobrokerW54"
host.iobrokerW54 check instance "system.adapter.discovery.0" for host "iobrokerW54"
host.iobrokerW54 check instance "system.adapter.backitup.0" for host "iobrokerW54"
object system.meta.uuid created: 3c0a46da-8c58-42f1-885d-dee487655a58
================================== > LOG REDIRECT system.adapter.admin.0 => true [system.adapter.admin.0.logging]
Send diag info: {"uuid":"3c0a46da-8c58-42f1-885d-dee487655a58","language":"de","country":"","hosts":[{"version":"4.0.24","platform":"Javascript/Node.js","type":"linux"}],"node":"v16.19.1","arch":"x64","docker":true,"adapters":{"admin":{"version":"6.3.5","platform":"Javascript/Node.js"},"discovery":{"version":"3.1.0","platform":"Javascript/Node.js"},"backitup":{"version":"2.5.12","platform":"Javascript/Node.js"}},"statesType":"jsonl","objectsType":"jsonl","noInstances":3,"compactMode":false,"noCompactInstances":0,"model":"Common KVM processor","cpus":2,"mem":4121370624,"ostype":"Linux","city":""}
================================== > LOG REDIRECT system.adapter.admin.0 => false [Process stopped]
================================== > LOG REDIRECT system.adapter.admin.0 => false [system.adapter.admin.0.logging]
```

**Comment by buanet** [comment]
Hi,
your way sounds correct. As there are some limitations at the docker default bridge network, I would prefer adding a new one and connecting iobroker and redis container to it. Like this example:

```
version: "2"
services:
  ####### ioBroker #######
  iobroker:
    container_name: iobrokertest
    image: ghcr.io/buanet/iobroker:v7.2.0
    hostname: iobrokertest
    restart: always
    networks:
      macvlan:
        ipv4_address: 192.168.xxx.xxx
      bridge:
    environment:
      - PACKAGES=nano
      - IOB_STATESDB_HOST=redis
      - IOB_STATESDB_PORT=6379
      - IOB_STATESDB_TYPE=redis
    volumes:
      - /volume1/docker/iobrokertest_data:/opt/iobroker
    depends_on:
      - redis
  ####### redis #######
  redis:
    container_name: redis
    image: redis:latest
    hostname: redis
    restart: always
    networks:
      bridge:
#    ports:
#      - "6379:6379" # no need to expose, as long as no connection from outside is needed
    volumes:
      - /volume1/docker/redis_data:/data

####### networks #######
networks:
  macvlan:
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: 192.168.xxx.xxx/24
          gateway: 192.168.xxx.1
          ip_range: 192.168.xxx.xxx/29
  bridge:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1
          ip_range: 172.18.0.1/24
```
But I have never used bluetooth together with that. As bluetooth is technically a network device, I'm not sure if this collides with the network configuration of your docker container then... It could also be needed to add some capabilities to the iobroker docker container, so it can fully access the network device.

Sorry, hope someone else can help you with that. 

Regards,
André

[NOTE] I converted this issue to a discussion. Please do not use Issues for support questions.
