### DISCUSSION TITLE
USBDEVICES on macOS as docker host

### DISCUSSION THREAD

**Discussion by fbiedka** [buanet/ioBroker.docker#366] [Questions & Answers / Fragen & Antworten] [answered]
First of all thanks for the great docker image.  

I try to connect my iobroker container to  an IR-reader (smartmeter, see details in [](https://bayha-electronics.de/tutorials/usb-lesekopf-iobroker/)) .   But the container stated:   **error gathering device information**

I checked the usb device multiple times and an iobroker installation without docker is working fine.

```
IPCam-Mac:iobroker fbiedka$ docker-compose up -d iobroker
[+] Running 1/2
 ✔ Container iobroker_db  Running                                                                                                                             0.0s 
 ⠿ Container iobroker     Starting                                                                                                                           17.8s 
Error response from daemon: error gathering device information while adding custom device "/dev/tty.wchusbserial1420": no such file or directory
IPCam-Mac:iobroker fbiedka$ ls /dev/tty.wc*
/dev/tty.wchusbserial1420
IPCam-Mac:iobroker fbiedka$ sw_vers
ProductName:	macOS
ProductVersion:	12.6.8
BuildVersion:	21G725
```

My docker-compose file :

```
version: "3.3"
services:
  iobroker:
    restart: always
    image: buanet/iobroker:latest
    container_name: iobroker
    hostname: iobroker
    ports:
      - 8081:8081
    volumes:
      - ./iobrokerdata:/opt/iobroker
    devices:
     - /dev/tty.wchusbserial1420:/dev/tty.wchusbserial1420
    environment:
      - USBDEVICES=/dev/tty.wchusbserial1420
    networks:
      - iobroker_net
    depends_on:
      - postgres
```

Output from iobroker (plain installation on mac os).
 
<img width="1047" alt="image" src="https://github.com/buanet/ioBroker.docker/assets/10513011/65477720-ab25-45e3-9d9c-02ebac3455eb">

Any idea or hints to solve the issue ? I prefer to keep the iobroker with postgres and grafana inside docker containers, the only challenge is to enable the USB device. 

Thanks for all comments in advance.
