### ISSUE TITLE
Restart unhealthy container

### ISSUE THREAD

**Issue by jpawlowski** [buanet/ioBroker.docker#270]
May I suggest to add something about [willfarrel/docker-autoheal](https://github.com/willfarrell/docker-autoheal) to the documentation?

A simple docker-compose.yml can look like this:

````yml
version: '3.1'

services:

  iobroker:
    image: buanet/iobroker:latest-v7
    restart: always
    container_name: iobroker
    volumes:
      - iobroker:/opt/iobroker
    labels:
      autoheal: true

  autoheal:
    image: willfarrell/autoheal
    restart: always
    container_name: autoheal
    #privileged: true    ## required on hosts with SELinux enabled, e.g. Fedora CoreOS
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
````
