### ISSUE TITLE
Raspberry Pi first start almost always fails (iobroker_startup.sh unary operator expected)

### ISSUE THREAD

**Issue by binarious** [buanet/ioBroker.docker#275]
I'm running this image on a Raspberry Pi with `restart: unless-stopped`, but the first autostart after booting almost always fails. When I restart the container, the booting completes.

**Log when startup fails**
```
iobroker_1  | --------------------------------------------------------------------------------
iobroker_1  | -------------------------     2022-08-02 22:19:12      -------------------------
iobroker_1  | --------------------------------------------------------------------------------
iobroker_1  |
iobroker_1  | --------------------------------------------------------------------------------
iobroker_1  | -----                 Welcome to your ioBroker-container!                  -----
iobroker_1  | -----                    Startupscript is now running.                     -----
iobroker_1  | -----                          Please be patient!                          -----
iobroker_1  | --------------------------------------------------------------------------------
iobroker_1  |
iobroker_1  | --------------------------------------------------------------------------------
iobroker_1  | -----                        Debugging information                         -----
iobroker_1  | -----                                                                      -----
iobroker_1  | -----                                System                                -----
iobroker_1  | -----                    arch:                aarch64                      -----
iobroker_1  | -----                    hostname:            41c951d0d961                 -----
iobroker_1  | -----                                                                      -----
iobroker_1  | -----                             Docker-Image                             -----
iobroker_1  | -----                    image:               v7.0.1                       -----
iobroker_1  | -----                    build:               2022-07-05T18:51:52+00:00    -----
iobroker_1  | -----                                                                      -----
iobroker_1  | -----                               Versions                               -----
iobroker_1  | -----                    node:                v16.16.0                     -----
iobroker_1  | -----                    npm:                 8.11.0                       -----
iobroker_1  | -----                                                                      -----
iobroker_1  | -----                                 ENV                                  -----
iobroker_1  | -----                    SETGID:              1000                         -----
iobroker_1  | -----                    SETUID:              1000                         -----
iobroker_1  | --------------------------------------------------------------------------------
iobroker_1  |
iobroker_1  | --------------------------------------------------------------------------------
iobroker_1  | -----                  Step 1 of 5: Preparing container                   -----
iobroker_1  | --------------------------------------------------------------------------------
iobroker_1  |
iobroker_1  | This is not the first run of this container. Skipping first run preparation.
iobroker_1  |
iobroker_1  | Installing additional packages is set by ENV.
iobroker_1  | Checking the following Packages: ...
iobroker_1  | E: Release file for http://deb.debian.org/debian/dists/bullseye-updates/InRelease is not valid yet (invalid for another 5h 58min 29s). Updates for this repository will not be applied.
iobroker_1  | Reading package lists...
iobroker_1  | Building dependency tree...
iobroker_1  | Reading state information...
iobroker_1  | Reading package lists...
iobroker_1  | Building dependency tree...
iobroker_1  | Reading state information...
iobroker_1  | 0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.
iobroker_1  | Done.
iobroker_1  |
iobroker_1  | --------------------------------------------------------------------------------
iobroker_1  | -----             Step 2 of 5: Detecting ioBroker installation             -----
iobroker_1  | --------------------------------------------------------------------------------
iobroker_1  |
iobroker_1  | Existing installation of ioBroker detected in /opt/iobroker.
iobroker_1  |
iobroker_1  | --------------------------------------------------------------------------------
iobroker_1  | -----             Step 3 of 5: Checking ioBroker installation              -----
iobroker_1  | --------------------------------------------------------------------------------
iobroker_1  |
iobroker_1  | (Re)Setting folder permissions (This might take a while! Please be patient!)... Done.
iobroker_1  |
iobroker_1  | Fixing "sudo-bug" by replacing sudo in iobroker with gosu... Done.
iobroker_1  |
iobroker_1  | /opt/scripts/iobroker_startup.sh: line 212: [: !=: unary operator expected
iobroker_1  | --------------------------------------------------------------------------------
iobroker_1  | -----                Step 4 of 5: Applying special settings                -----
iobroker_1  | --------------------------------------------------------------------------------
iobroker_1  |
iobroker_1  | Some adapters have special requirements/ settings which can be activated by the use of environment variables.
iobroker_1  | For more information see ioBroker Docker Image Docs (https://docs.buanet.de/iobroker-docker-image/docs/).
iobroker_1  |
iobroker_1  | --------------------------------------------------------------------------------
iobroker_1  | -----                    Step 5 of 5: ioBroker startup                     -----
iobroker_1  | --------------------------------------------------------------------------------
iobroker_1  |
iobroker_1  | Starting ioBroker...
iobroker_1  |
```

**Log after restarting the container**
```
iobroker_1  | --------------------------------------------------------------------------------
iobroker_1  | -------------------------     2022-08-02 09:41:45      -------------------------
iobroker_1  | --------------------------------------------------------------------------------
iobroker_1  |
iobroker_1  | --------------------------------------------------------------------------------
iobroker_1  | -----                 Welcome to your ioBroker-container!                  -----
iobroker_1  | -----                    Startupscript is now running.                     -----
iobroker_1  | -----                          Please be patient!                          -----
iobroker_1  | --------------------------------------------------------------------------------
iobroker_1  |
iobroker_1  | --------------------------------------------------------------------------------
iobroker_1  | -----                        Debugging information                         -----
iobroker_1  | -----                                                                      -----
iobroker_1  | -----                                System                                -----
iobroker_1  | -----                    arch:                aarch64                      -----
iobroker_1  | -----                    hostname:            41c951d0d961                 -----
iobroker_1  | -----                                                                      -----
iobroker_1  | -----                             Docker-Image                             -----
iobroker_1  | -----                    image:               v7.0.1                       -----
iobroker_1  | -----                    build:               2022-07-05T18:51:52+00:00    -----
iobroker_1  | -----                                                                      -----
iobroker_1  | -----                               Versions                               -----
iobroker_1  | -----                    node:                v16.16.0                     -----
iobroker_1  | -----                    npm:                 8.11.0                       -----
iobroker_1  | -----                                                                      -----
iobroker_1  | -----                                 ENV                                  -----
iobroker_1  | -----                    SETGID:              1000                         -----
iobroker_1  | -----                    SETUID:              1000                         -----
iobroker_1  | --------------------------------------------------------------------------------
iobroker_1  |
iobroker_1  | --------------------------------------------------------------------------------
iobroker_1  | -----                  Step 1 of 5: Preparing container                   -----
iobroker_1  | --------------------------------------------------------------------------------
iobroker_1  |
iobroker_1  | This is not the first run of this container. Skipping first run preparation.
iobroker_1  |
iobroker_1  | Installing additional packages is set by ENV.
iobroker_1  | Checking the following Packages: ...
iobroker_1  | Reading package lists...
iobroker_1  | Building dependency tree...
iobroker_1  | Reading state information...
iobroker_1  | Reading package lists...
iobroker_1  | Building dependency tree...
iobroker_1  | Reading state information...
iobroker_1  | 0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.
iobroker_1  | Done.
iobroker_1  |
iobroker_1  | --------------------------------------------------------------------------------
iobroker_1  | -----             Step 2 of 5: Detecting ioBroker installation             -----
iobroker_1  | --------------------------------------------------------------------------------
iobroker_1  |
iobroker_1  | Existing installation of ioBroker detected in /opt/iobroker.
iobroker_1  |
iobroker_1  | --------------------------------------------------------------------------------
iobroker_1  | -----             Step 3 of 5: Checking ioBroker installation              -----
iobroker_1  | --------------------------------------------------------------------------------
iobroker_1  |
iobroker_1  | (Re)Setting folder permissions (This might take a while! Please be patient!)... Done.
iobroker_1  |
iobroker_1  | Fixing "sudo-bug" by replacing sudo in iobroker with gosu... Done.
iobroker_1  |
iobroker_1  | --------------------------------------------------------------------------------
iobroker_1  | -----                Step 4 of 5: Applying special settings                -----
iobroker_1  | --------------------------------------------------------------------------------
iobroker_1  |
iobroker_1  | Some adapters have special requirements/ settings which can be activated by the use of environment variables.
iobroker_1  | For more information see ioBroker Docker Image Docs (https://docs.buanet.de/iobroker-docker-image/docs/).
iobroker_1  |
iobroker_1  | --------------------------------------------------------------------------------
iobroker_1  | -----                    Step 5 of 5: ioBroker startup                     -----
iobroker_1  | --------------------------------------------------------------------------------
iobroker_1  |
iobroker_1  | Starting ioBroker...
iobroker_1  |
iobroker_1  | ================================== > LOG REDIRECT system.adapter.admin.0 => true [starting]
iobroker_1  | host.41c951d0d961 check instance "system.adapter.admin.0" for host "41c951d0d961"
iobroker_1  | host.41c951d0d961 check instance "system.adapter.javascript.0" for host "41c951d0d961"
iobroker_1  | host.41c951d0d961 check instance "system.adapter.influxdb.0" for host "41c951d0d961"
iobroker_1  | host.41c951d0d961 check instance "system.adapter.mqtt.0" for host "41c951d0d961"
iobroker_1  | host.41c951d0d961 check instance "system.adapter.weatherunderground.0" for host "41c951d0d961"
iobroker_1  | host.41c951d0d961 check instance "system.adapter.discovery.0" for host "41c951d0d961"
iobroker_1  | host.41c951d0d961 check instance "system.adapter.backitup.0" for host "41c951d0d961"
iobroker_1  | host.41c951d0d961 check instance "system.adapter.matrix-org.0" for host "41c951d0d961"
iobroker_1  | Adding default global override for .org.matrix.msc3786.rule.room.server_acl
iobroker_1  |
iobroker_1  | Adding default global override for .org.matrix.msc3786.rule.room.server_acl
```

**docker-compose.yml**
```
version: '3'

services:
  iobroker:
    image: buanet/iobroker:latest-v7
    volumes:
      - data:/opt/iobroker
    restart: unless-stopped
    expose:
      - 8081
    ports:
      - "8084:8084"
      - "8883:8883"
    environment:
      VIRTUAL_HOST: iobroker.cloud
      VIRTUAL_PORT: 8081
      CERT_NAME: default
      HTTPS_METHOD: noredirect

  influx:
    image: docker.io/library/influxdb:2.3-alpine
    volumes:
      - influxdb:/var/lib/influxdb2
      - influxdb-config:/etc/influxdb2
    restart: unless-stopped
    environment:
      DOCKER_INFLUXDB_INIT_USERNAME: REDACTED
      DOCKER_INFLUXDB_INIT_PASSWORD: REDACTED
      DOCKER_INFLUXDB_INIT_ORG: influx
      DOCKER_INFLUXDB_INIT_BUCKET: iobroker
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: REDACTED
      DOCKER_INFLUXDB_INIT_MODE: setup

  grafana:
    image: docker.io/grafana/grafana:9.0.5
    restart: always
    user: "1000:100"
    environment:
      - CERT_NAME=default
      - VIRTUAL_HOST=grafana.cloud
    volumes:
      - grafana:/var/lib/grafana

volumes:
  data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "${PWD}/volumes/data"
  influxdb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "${PWD}/volumes/influxdb"
  influxdb-config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "${PWD}/volumes/influxdb-config"
  grafana:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "${PWD}/volumes/grafana"

networks:
    default:
        external:
            name: nginx-proxy
```

**System**
- Raspberry Pi 4
- Kernel 5.10.103
- Docker-Compose 1.28.4
- Docker 20.10.17
- Volumes are simple folders (no mounts, etc.)

Maybe related: https://github.com/buanet/ioBroker.docker/issues/271

**Comment by yreiser** [comment]
I had the same issue. Turned out that I had another service running on port 9001 (in my case, Mosquitto Websocket Port). Check if ports 9000 and 9001 are not used by any other server running on the same network.

**Comment by binarious** [comment]
Thanks for the hint, but I don't have another service running on that port.

**Comment by buanet** [comment]
hi,
your environment variables are not supported. please see [docs](https://docs.buanet.de/iobroker-docker-image/docs/#environment-variables-env) for valid variables. 
```
    environment:
      VIRTUAL_HOST: iobroker.cloud
      VIRTUAL_PORT: 8081
      CERT_NAME: default
      HTTPS_METHOD: noredirect
```
Are there any reasons why your 8081 port is listed in expose not like the others in ports?
```
    expose:
      - 8081
    ports:
      - "8084:8084"
      - "8883:8883"
```
Not sure if this makes any difference...

regards,
André
