### ISSUE TITLE
[Problem]: Erstinstallation iobroker auf Synology via Portainer: Checking database connection... Failed.

### ISSUE THREAD

**Issue by xannasavin** [buanet/ioBroker.docker#505]
### Description / Beschreibung

Hi,
ich versuche gerade iobroker das erste Mal auf meiner Synology via Portainer anhand [dieser Anleitung](https://blog.buanet.de/posts/2023/02/27_iobroker_unter_docker_auf_der_synology_diskstation/#bonus-container-mit-portainer-stacks-erstellen) zu installieren.
Leider erhalte ich beim Deploy des Stacks die Fehlermeldung "Checking database connection... Failed."
Das Script ist ja eigentlich recht simpel, daher bin ich mir nicht sicher, wo das Problem liegen könnte...

Nachfolgend mein Setup - falls noch etwas fehlt bitte Bescheid geben.

Und viele Dank im Voraus für jegliche Hilfe!

Synology DS918+ (DSM Version 7.1.1-42962)
Docker 20.10.3-1308
Portainer Community Edition 2.21.3
image:               v10.0.0
build:               2024-10-18T02:20:16+02:00
node:                v20.18.0  
npm:                 10.8.2  

YAML:
`````
services:
  iobroker:
    image: buanet/iobroker:latest
    container_name: iobroker
    restart: on-failure:5
    ports:
      - 8081:8081 
    volumes:
      - /volume1/docker/iobroker-data:/opt/iobroker
    environment:
      SETUID: 1036
      SETGID: 100
      PACKAGES: nano
    healthcheck:
      test: ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:8081"]
      interval: 30s
      timeout: 10s
      retries: 5
    security_opt:
      - no-new-privileges:true
`````

1036 = UserID des Docker Users, dem der Docker Shared Folder gehört.

### Image version

10.0.0

### Docker logs / Docker Protokoll

```shell
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
-----                   Step 1 of 5: Preparing Container                   -----
--------------------------------------------------------------------------------

PACKAGES is set. Installing the following additional Linux packages: nano
 
nano is already installed.

 SETUID and/ or SETGID are set to custom values.

Changing UID to "1036" and GID to "100"... usermod: no changes

Done.

 --------------------------------------------------------------------------------
-----             Step 2 of 5: Detecting ioBroker Installation             -----
--------------------------------------------------------------------------------

Existing installation of ioBroker detected in "/opt/iobroker".

 --------------------------------------------------------------------------------
-----             Step 3 of 5: Checking ioBroker Installation              -----
--------------------------------------------------------------------------------

 (Re)setting permissions (This might take a while! Please be patient!)... Done.

Checking database connection... Failed.

[ERROR] Error: no UUID found

 Please check your configuration and try again.

For more information see ioBroker Docker image docs (https://docs.buanet.de/iobroker-docker-image/docs).

 This Script will exit now.

 --------------------------------------------------------------------------------
-------------------------     2024-11-15 08:55:42      -------------------------
--------------------------------------------------------------------------------
-----                                                                      -----
----- ██╗  ██████╗  ██████╗  ██████╗   ██████╗  ██╗  ██╗ ███████╗ ██████╗  -----
----- ██║ ██╔═══██╗ ██╔══██╗ ██╔══██╗ ██╔═══██╗ ██║ ██╔╝ ██╔════╝ ██╔══██╗ -----
----- ██║ ██║   ██║ ██████╔╝ ██████╔╝ ██║   ██║ █████╔╝  █████╗   ██████╔╝ -----
----- ██║ ██║   ██║ ██╔══██╗ ██╔══██╗ ██║   ██║ ██╔═██╗  ██╔══╝   ██╔══██╗ -----
----- ██║ ╚██████╔╝ ██████╔╝ ██║  ██║ ╚██████╔╝ ██║  ██╗ ███████╗ ██║  ██║ -----
----- ╚═╝  ╚═════╝  ╚═════╝  ╚═╝  ╚═╝  ╚═════╝  ╚═╝  ╚═╝ ╚══════╝ ╚═╝  ╚═╝ -----
-----                                                                      -----
-----              Welcome to your ioBroker Docker container!              -----
-----                    Startupscript is now running!                     -----
-----                          Please be patient!                          -----
--------------------------------------------------------------------------------

 --------------------------------------------------------------------------------
-----                          System Information                          -----
-----                    arch:                x86_64                       -----
-----                    hostname:            b13ac873a0d8                 -----
-----                                                                      -----
-----                          Version Information                         -----
-----                    image:               v10.0.0                      -----
-----                    build:               2024-10-18T02:20:16+02:00    -----
-----                    node:                v20.18.0                     -----
-----                    npm:                 10.8.2                       -----
-----                                                                      -----
-----                        Environment Variables                         -----
-----                    PACKAGES:            nano                         -----
-----                    SETGID:              100                          -----
-----                    SETUID:              1036                         -----
--------------------------------------------------------------------------------

 --------------------------------------------------------------------------------
-----                   Step 1 of 5: Preparing Container                   -----
--------------------------------------------------------------------------------

 PACKAGES is set. Installing the following additional Linux packages: nano

 nano is already installed.

 
SETUID and/ or SETGID are set to custom values.

Changing UID to "1036" and GID to "100"... usermod: no changes

Done.

 --------------------------------------------------------------------------------
-----             Step 2 of 5: Detecting ioBroker Installation             -----
--------------------------------------------------------------------------------

Existing installation of ioBroker detected in "/opt/iobroker".

 --------------------------------------------------------------------------------
-----             Step 3 of 5: Checking ioBroker Installation              -----
--------------------------------------------------------------------------------

(Re)setting permissions (This might take a while! Please be patient!)... Done.

Checking database connection... Failed.

[ERROR] Error: no UUID found

Please check your configuration and try again.

For more information see ioBroker Docker image docs (https://docs.buanet.de/iobroker-docker-image/docs).

This Script will exit now.
```

**Comment by xannasavin** [comment]
Die YAML auf das absolute Minimum zu reduzieren hat nichts gebracht:

````
services:
  iobroker:
    image: buanet/iobroker:latest
    container_name: iobroker
    restart: on-failure:5
    ports:
      - 8081:8081 
    volumes:
      - /volume1/docker/iobroker-data:/opt/iobroker
    environment:
      PACKAGES: nano
````
