### ISSUE TITLE
[Problem]: Container does not start with NFS mount

### ISSUE THREAD

**Issue by crosenbe** [buanet/ioBroker.docker#509]
### Description / Beschreibung

If the container will be configured with a NFS path to store backups before ioBroker was initially started data are detected and the installation stops. There are two workarounds.

1. Mount the NFS after the initialization.
2. Change the kind how data are detected.

Inside the container the function copy backup to NAS does not work because rpc-statd is missing, the NFS mount inside of the container does not work. Mounting the backup folder via NFS as a volume solve this problem, but with the limitation described above.

Maybe following change can be a potential solution ...

`if [[ `find /opt/iobroker -type f **-maxdepth 1** | wc -l` -lt 1 ]]; then`

**Kubernetes YAML**
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iobroker
  namespace: home
spec:
  selector:
    matchLabels:
      app: iobroker
  replicas: 1
  template:
    metadata:
      name: iobroker
      labels:
        app: iobroker
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
      hostname: iobroker
      containers:
        - name: iobroker
          image: buanet/iobroker:latest-v10
          resources:
            requests:
              memory: "500Mi"
              cpu: "50m"
            limits:
              memory: "500Mi"
              cpu: "500m"
          ports:
            - containerPort: 8081 # admin
            - containerPort: 8087 # SimpleAPI SSL
            - containerPort: 8089 # SimpleAPI
            - containerPort: 8091 # Backup Web
            - containerPort: 9081 # Backup Download
            - containerPort: 9082 # Backup Upload
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - '[ -f "/tmp/liveness-status" ] || curl -k -f https://localhost:8081/status >/dev/null 2>&1'
            initialDelaySeconds: 600 
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 40 
          env:
          env:
            - name: TZ
              value: Europe/Berlin
          volumeMounts:
            - name: iobroker-data
              mountPath: /opt/iobroker
            - name: iobroker-backup
              mountPath: /opt/iobroker/backups
          securityContext:
            appArmorProfile:
              type: Unconfined
            capabilities:
              add:
                - SYS_ADMIN
            privileged: true
      volumes:
        - name: iobroker-data
          persistentVolumeClaim:
            claimName: iobroker-data-pvc
        - name: iobroker-backup
          nfs:
            server: 10.10.10.10
            path: /iobroker_backup

```

### Image version

:latest-v10

### Docker logs / Docker Protokoll

```shell
n/a
```
